# -*- coding: utf-8 -*-
"""Leaf-Similar_Trees.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10moqEVyYP18j9I_YLTLob5v4fDddTXlu
"""

# Definition for a binary tree node.
class TreeNode(object):
     def __init__(self, val=0, left=None, right=None):
         self.val = val
         self.left = left
         self.right = right
class Solution(object):
    def leafSimilar(self, root1, root2):
      def dfs(root, leaf):
        if not root:
          return
        if not root.left and not root.right:
          leaf.append(root.value)
        dfs(root.left, leaf)
        dfs(root.right, leaf)
      leaf1 = []
      leaf2 = []
      dfs(root1, leaf1)
      dfs(root2, leaf2)
      return leaf1 == leaf2