# -*- coding: utf-8 -*-
"""Longest Substring Without Repeating Characters.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bdUOgK21XGJUeh9ml5rfow8fgP6pd25C
"""

class Solution(object):
    def lengthOfLongestSubstring(self, s):
          sett = set()
          l = 0
          longest = 0
          for r in range(len(s)):
             while s[r] in sett:
                sett.remove(s[l])
                l = l +1
             sett.add(s[r])
             longest = max(longest, r-l+1)
          return longest