# -*- coding: utf-8 -*-
"""Merge Strings Alternately.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e30NIfA_-2xXJbRCYEnMrt6Xgv4U2dBO
"""

class Solution(object):
    def isPalindrome(self, x):
        ss = [y for y in str(x)]
        if ss == ss[::-1]:
          return True
        else:
          return False

s =-12
ss = [y for y in str(s)]
ss

ss[::-1]

class Solution(object):
    def isPalindrome(self, x):
      if str(x) [::-1] == str(x) :
        return True
      else:
        return False

class Solution(object):
    def mergeAlternately(self, word1, word2):
        l = 0
        w = ""
        while l < max (len(word1),len(word2)):
            w1 = word1[l] if l < len(word1) else ""
            w2 = word2[l] if l < len(word2) else ""
            w = w + w1 + w2
            l = l + 1
        return w

sol = Solution()

sol.mergeAlternately("ab","pqrs")