# -*- coding: utf-8 -*-
"""Minimum Number of Changes to Make Binary String Beautiful.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yDT8nv65c7tvNN_TjOQ7geIPNbtV_xuC
"""

class Solution(object):
    def minChanges(self, s):
       spl= 2
       c = 0
       while s:
          g, s=s[:spl],s[spl:]
          if g.count(g[0]) != len(g):
                c = c+1
       return c

ff = Solution()

ff.minChanges("0101")