# -*- coding: utf-8 -*-
"""palinimdrome number.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kizL7dWbSL6NoOLkmqsxnYecY93GxXLs

Given an integer x, return true if x is a
palindrome
, and false otherwise.
"""

class Solution(object):
    def isPalindrome(self, x):
      if str(x) [::-1] == str(x) :
        return True
      else:
        return False